LEX=flex
LFLAGS=-l
YACC=yacc
YFLEGS=-vd
CC=gcc
CCFLAGS=-Wall -g
CCYFLAGS=-DYYDEBUG -ly -lfl

parser: 
	$(LEX) $(LFLAGS) -o lex/lex.daitsch.c lex/daitsch.l
	$(YACC) ${YFLEGS} -o yacc/yacc.daitsch.c yacc/daitsch_condition.y
	$(CC) $(CCFLAGS) -c -o lib/symbol_table.o lib/symbol_table.c
	$(CC) $(CCFLAGS) $(CCYFLAGS)-o bin/parser yacc/yacc.daitsch.c lib/symbol_table.o

